name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Cambia esto a la rama que desees

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'  
          distribution: 'temurin'

      - name: Compile code with Maven
        run: mvn clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: juanmigueld/api_names:1.3
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout Helm charts repository
        uses: actions/checkout@v3
        with:
          repository: JuanMiguelD/api-names_chart  # Cambia esto al nombre de tu repositorio de charts
          path: charts
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Helm chart
        run: |
          cd charts/api-names_chart  # Cambia esto a la ruta correcta dentro del repositorio de charts
          sed -i "s/^version: .*/version: 1.3/" Chart.yaml  # Actualiza la versión del chart
          sed -i "s/^appVersion: .*/appVersion: 1.3/" Chart.yaml  # Actualiza la versión de la aplicación
          helm dependency update
          helm package .
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update chart to version 1.3"
          git push origin main