name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21' 
          distribution: 'temurin'

      # Paso 3: Compilar el código con Maven
      - name: Compile code with Maven
        run: mvn clean package

      # Paso 4: Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 5: Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Paso 6: Construir y subir la imagen de Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: juanmigueld/api_names:1.3
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Paso 7: Checkout del repositorio del Helm chart (helmApi)
      - name: Checkout Helm chart repository (helmApi)
        uses: actions/checkout@v3
        with:
          repository: JuanMiguelD/helmApi  
          path: helm-chart  
          token: ${{ secrets.GITHUB_TOKEN }}

      # Paso 8: Empaquetar el Helm chart
      - name: Package Helm chart
        run: |
          cd helm-chart  # Cambia al directorio del chart
          sed -i "s/^version: .*/version: 1.3/" Chart.yaml  # Actualiza la versión del chart
          sed -i "s/^appVersion: .*/appVersion: 1.3/" Chart.yaml  # Actualiza la versión de la aplicación
          helm dependency update
          helm package .

      # Paso 9: Checkout del repositorio de Helm (api-names_chart)
      - name: Checkout Helm repository (api-names_chart)
        uses: actions/checkout@v3
        with:
          repository: JuanMiguelD/api-names_chart
          path: helm-repo
          token: ${{ secrets.GITHUB_TOKEN }}  # Usa el GITHUB_TOKEN
          ssh-strict: true
          persist-credentials: true
          clean: true
          sparse-checkout-cone-mode: true
          fetch-depth: 1
          fetch-tags: false
          lfs: false
          submodules: false
          set-safe-directory: true
      # Paso 10: Actualizar el repositorio de Helm
      - name: Update Helm repository
        run: |
          cd helm-repo  # Cambia al directorio del repositorio de charts
          cp ../helm-chart/*.tgz .  # Copia el chart empaquetado
          helm repo index .  # Actualiza el index.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update chart to version 1.3"
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/JuanMiguelD/api-names_chart.git
          git push origin main