name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21' 
          distribution: 'temurin'

      - name: Compile code with Maven
        run: mvn clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: juanmigueld/api_names:1.3
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout Helm chart repository (helmApi)
        uses: actions/checkout@v3
        with:
          repository: JuanMiguelD/helmApi  
          path: helm-chart  
          token: ${{ secrets.TOKEN_GITHUB }}

      - name: Package Helm chart
        run: |
          cd helm-chart  # Cambia al directorio del chart
          sed -i "s/^version: .*/version: 1.3/" Chart.yaml  # Actualiza la versión del char
          sed -i "s/^appVersion: .*/appVersion: 1.3/" Chart.yaml  # Actualiza la versión de la aplicación
          helm dependency update
          helm package .

      - name: Checkout Helm repository (api-names_chart)
        uses: actions/checkout@v3
        with:
          repository: JuanMiguelD/api-names_chart  
          path: helm-repo  
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Helm repository
        run: |
          cd helm-repo  # Cambia al directorio del repositorio de charts
          cp ../helm-chart/*.tgz .  # Copia el chart empaquetado
          helm repo index .  # Actualiza el index.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update chart to version 1.3"
          git push origin main