name: Build and Update Helm Values
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'docs/**'

env:
  HELM_REPO: "JuanMiguelD/helmApi"
  APP_NAME: "api_names"
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build_and_update_helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout application code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image
        uses: docker/build-push-action@v4
        env:
          IMAGE_TAG: ${{ github.sha }}
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api_names:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/api_names:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout Helm repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.HELM_REPO }}
          token: ${{ secrets.HELM_REPO_PAT }}
          path: helm-charts

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Update Helm values
        run: |
          cd helm-charts
          if [ ! -f values.yaml ]; then
            echo "Error: values.yaml not found in expected location"
            exit 1
          fi
          yq eval ".image.repository = \"${{ secrets.DOCKERHUB_USERNAME }}/api_names\"" -i values.yaml
          yq eval ".image.tag = \"${{ github.sha }}\"" -i values.yaml
          yq eval ".image.pullPolicy = \"Always\"" -i values.yaml

      - name: Commit and push Helm changes
        run: |
          cd helm-charts
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "chore: update image tag to ${{ github.sha }} and repository path"
          git push
