name: Build and Update Helm Values
on:
  push:
    branches: [ Dev ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'docs/**'

env:
  REGISTRY: "registry.digitalocean.com"
  IMAGE_NAME: ${{ github.repository }}
  HELM_REPO: "JuanMiguelD/helmApi"
  APP_NAME: "api-names"

jobs:
  build_and_update_helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout application code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Modificamos la construcción y push de la imagen para usar tu estructura
      - name: Build and push image
        uses: docker/build-push-action@v4
        env:
          IMAGE_TAG: ${{ github.sha }}
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/juanmigueld/api_names:${{ github.sha }}
            ${{ env.REGISTRY }}/juanmigueld/api_names:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout Helm repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.HELM_REPO }}
          token: ${{ secrets.HELM_REPO_PAT }}
          path: helm-charts

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      # Actualizamos el values.yaml manteniendo la estructura existente
      - name: Update Helm values
        run: |
          cd helm-charts
          if [ ! -f values.yaml ]; then
            echo "Error: values.yaml not found in expected location"
            exit 1
          fi
          yq eval ".image.repository = \"$REGISTRY/juanmigueld/api_names\"" -i values.yaml
          yq eval ".image.tag = \"${{ github.sha }}\"" -i values.yaml
          yq eval ".image.pullPolicy = \"Always\"" -i values.yaml

      - name: Commit and push Helm changes
        run: |
          cd helm-charts
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "chore: update image tag to ${{ github.sha }} and repository path"
          git push
